name: Build and Publish .NET Framework 4.8

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET Framework 4.8 build environment
      - name: Setup .NET Framework 4.8
        run: |
          Install-WindowsFeature -Name NET-Framework-Features
      
      - name: Install NuGet CLI
        uses: nuget/setup-nuget@v1
      
      # Restore NuGet packages (if applicable)
      - name: Restore NuGet packages
        run: nuget restore
        
      - name: Find MSBuild Path
        id: msbuild
        run: |
          $msbuildPath = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          echo "MSBUILD_PATH=$msbuildPath" >> $env:GITHUB_ENV
      
      - name: Build solution using MSBuild
        run: |
          & $env:MSBUILD_PATH "WebApplicationMy.sln" /p:Configuration=Release

      - name: Publish project using MSBuild
        run: |
          & $env:MSBUILD_PATH "${{ github.workspace }}/WebApplicationMy/WebApplicationMy.csproj" /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:PublishDir="${{ github.workspace }}/publish" /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=true

      - name: List published files
        run: dir ${{ github.workspace }}\publish

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp-publish
          path: ${{ github.workspace }}/publish


      - name: publish
        shell: cmd
        run: |
          if exist "$(System.DefaultWorkingDirectory)/publish/*" (
              xcopy /s /y "$(System.DefaultWorkingDirectory)/publish" "D:\Ahtesham ul haq\Projects\Learning\Github\webdeploy\publish\"
          ) else (
              echo "No files to copy"
          )

