name: Build and Publish .NET Framework 4.8

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET Framework 4.8 build environment
      - name: Setup .NET Framework 4.8
        run: |
          Install-WindowsFeature -Name NET-Framework-Features
      
      # Install NuGet CLI
      - name: Install NuGet CLI
        uses: nuget/setup-nuget@v1
      
      # Restore NuGet packages (if applicable)
      - name: Restore NuGet packages
        run: nuget restore
        
      # Find MSBuild Path
      - name: Find MSBuild Path
        id: msbuild
        run: |
          $msbuildPath = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          echo "MSBUILD_PATH=$msbuildPath" >> $env:GITHUB_ENV
      
      # Build solution using MSBuild
      - name: Build solution using MSBuild
        run: |
          & $env:MSBUILD_PATH "${{ github.workspace }}/WebApplicationMy.sln" /p:Configuration=Release /p:OutputPath="${{ github.workspace }}/build_output"

      # List files in build output directory
      - name: List files in build output directory
        run: |
          Get-ChildItem -Path "${{ github.workspace }}/build_output" -Recurse

      # Copy build output to publish directory
      - name: Copy build output to publish directory
        run: |
          Copy-Item -Path "${{ github.workspace }}/build_output\*" -Destination "${{ github.workspace }}/publish" -Recurse -Force
