name: Build and Publish .NET Framework 4.8

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET Framework 4.8 build environment
      - name: Setup .NET Framework 4.8
        run: |
          Install-WindowsFeature -Name NET-Framework-Features
      
      - name: Install NuGet CLI
        uses: nuget/setup-nuget@v1
      
      # Restore NuGet packages (if applicable)
      - name: Restore NuGet packages
        run: nuget restore
        
      - name: Find MSBuild Path
        id: msbuild
        run: |
          $msbuildPath = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          echo "MSBUILD_PATH=$msbuildPath" >> $env:GITHUB_ENV
      
      - name: Build solution using MSBuild
        run: |
          & $env:MSBUILD_PATH "${{ github.workspace }}/WebApplicationMy.sln" /p:Configuration=Release /p:OutputPath="${{ github.workspace }}/build_output"

      - name: List files in build output directory
        run: |
          Get-ChildItem -Path "${{ github.workspace }}/build_output" -Recurse

      - name: Copy build output to publish directory
        run: |
          Copy-Item -Path "${{ github.workspace }}/build_output" -Destination "${{ github.workspace }}/publish" -Recurse -Force

      - name: Copy published files
        run: |        
          Copy-Item -Path "D:\Ahtesham ul haq\Projects\Learning\Github\webdeploy\actions-runner\_work\mygit\mygit\publish\_PublishedWebsites\WebApplicationMy\*" -Destination "D:\Ahtesham ul haq\Projects\Learning\Github\webdeploy\publish" -Recurse -Force
      
   




