name: Build and Publish .NET Framework 4.8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET Framework 4.8 build environment
      - name: Setup .NET Framework 4.8
        run: |
          Install-WindowsFeature -Name NET-Framework-Features

      # Restore NuGet packages (if applicable)
      - name: Restore NuGet packages
        run: nuget restore

      # Build the project
      - name: Build solution using MSBuild
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe" WebApplicationMy.sln /p:Configuration=Release

      # Publish artifacts (if applicable)
      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            **/bin/Release/*
